app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
    # Group urls
    path('',views.group, name='group'),
    path('group_add/', views.group_add, name='group_add'),
    path('group_update/<uuid:id>/', views.group_update, name='group_update'),
    path('group_delete/<uuid:id>/', views.group_delete, name='group_delete'),

    # Users urls
    path('users/', views.users, name='users'),
    path('users_add/', views.users_add, name='users_add'),
    
]

role_permission/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'),)
]

templates/footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>AUDM</b> ...
    </div>
    <strong>Copyright &copy; 2023
  </footer>

templates/group.html
{% load static cutom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>

  <!-- Google Font: Source Sans Pro -->
  <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  {% include 'nav.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><i class="fa fa-users"></i> Toparlar</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <a href="{% url 'app:group_add' %}">
                <button type="button" class="btn btn-primary btn-block"><i class="fa fa-plus"></i> Topar goş</button>
              </a>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>Ady</th>
                    <th>Rugsatlary</th>
                    <th>Degişli ulanjylar</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for group in groups %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ group.name }}</td>
                    <td>
                      {% for permission in group.permission|split:"," %}
                      <mark>{{ permission }}</mark>
                      {% endfor %}
                    </td>
                    <td>
                      {% for group_user in group.users.all %}
                      <mark>{{ group_user }}</mark>
                      {% endfor %}
                    </td>
                    <td>
                      <div class="margin">
                        <!-- <div class="btn-group">
                          <a href="#" class="btn btn-outline-primary btn-block"><i class="fa fa-eye"></i></a>
                        </div> -->
                        <div class="btn-group">
                          <a href="{% url 'app:group_update' group.id %}" class="btn btn-outline-success btn-block"><i class="fa fa-edit"></i></a>
                        </div>
                        <div class="btn-group">
                          <a href="{% url 'app:group_delete' group.id %}" class="btn btn-outline-danger btn-block" data-toggle="modal" data-target="#modal-lg{{ group.id }}"><i class="fa fa-trash"></i></a>
                          <div class="modal fade" id="modal-lg{{ group.id }}">
                            <div class="modal-dialog modal-lg">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h4 class="modal-title">Topar pozmak</h4>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <div class="modal-body">
                                  <h6>Ady: <em style="color: red;">{{ group.name }}</em></h6>
                                  <hr>
                                  <h6>
                                    Rugsatlar:
                                    {% for permission in group.permission|split:"," %}
                                    <mark style="color: red;">{{ permission }}</mark>
                                    {% endfor %}
                                  </h6>
                                  <hr>
                                  <h6>
                                    Degişli ulanjylar:
                                    {% for group_user in group.users.all %}
                                    <mark style="color: red;">{{ group_user }}</mark>
                                    {% endfor %}
                                  </h6>
                                </div>
                                <div class="modal-footer justify-content-between">
                                  <button type="button" class="btn btn-default" data-dismiss="modal">Yza</button>
                                  <button type="button" class="btn btn-danger">Tassykla</button>
                                </div>
                              </div>
                              <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                  <tfoot>
                    <tr>
                      <th>#</th>
                      <th>Ady</th>
                      <th>Rugsatlary</th>
                      <th>Degişli ulanjylar</th>
                      <th>Action</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'footer.html' %}

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!-- <script src="{% static 'dist/js/demo.js' %}"></script> -->
<!-- Page specific script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, 
      "lengthChange": false, 
      "autoWidth": false,
      "pageLength":50,
      // "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
      "buttons": ["colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    
    
  });
</script>
{% include 'message.html' %}
</body>
</html>

templates/group_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>

  <!-- Google Font: Source Sans Pro -->
  <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
     <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  {% include 'nav.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Topar goşmak</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'app:group' %}">Toparlar</a></li>
              <li class="breadcrumb-item active">Topar gos</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3"></div>
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Formy doldyryň</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{% url 'app:group_add' %}" method="post">{% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Toparyň ady</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" name="group_name" placeholder="Toparyň ady">
                  </div>
                  <div class="form-group">
                    <label>Rugsatlar</label>
                    <select class="duallistbox" multiple="multiple" name="permissions">
                      {% for permission in permissions %}
                      <option value="{{ permission.0 }}">{{ permission.1 }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Degişli ulanjylar</label>
                    <select class="duallistbox2" multiple="multiple" name="users">
                      {% for user in users %}
                      <option value="{{ user }}">{{ user }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Ýatda sakla</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>
          <div class="col-md-3"></div>
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'footer.html' %}

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!-- <script src="{% static 'dist/js/demo.js' %}"></script> -->
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
//Bootstrap Duallistbox
$('.duallistbox').bootstrapDualListbox()
$('.duallistbox2').bootstrapDualListbox()
</script>
{% include 'message.html' %}
</body>

templates/group_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>

  <!-- Google Font: Source Sans Pro -->
  <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
     <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  {% include 'nav.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Topar Uygetmek</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'app:group' %}">Toparlar</a></li>
              <li class="breadcrumb-item active">Topar gos</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3"></div>
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Formy uytgedin</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{% url 'app:group_update' group.id %}" method="post">{% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Toparyň ady</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" name="group_name" placeholder="Toparyň ady" value="{{ group.name }}">
                  </div>
                  <div class="form-group">
                    <label>Rugsatlar</label>
                    <select class="duallistbox" multiple="multiple" name="permissions">
                      {% for permission in permissions %}
                      {% if permission.0 in group.permission %}
                      <option value="{{ permission.0 }}" selected>{{ permission.1 }}</option>
                      {% else %}
                      <option value="{{ permission.0 }}">{{ permission.1 }}</option>
                      {% endif %}
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Degişli ulanjylar</label>
                    <select class="duallistbox2" multiple="multiple" name="users">
                      {% for user in users %}
                      {% if user in group.users.all %}
                      <option value="{{ user }}" selected>{{ user }}</option>
                      {% else %}
                      <option value="{{ user }}">{{ user }}</option>
                      {% endif %}
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Ýatda sakla</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>
          <div class="col-md-3"></div>
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  {% include 'footer.html' %}

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!-- <script src="{% static 'dist/js/demo.js' %}"></script> -->
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
//Bootstrap Duallistbox
$('.duallistbox').bootstrapDualListbox()
$('.duallistbox2').bootstrapDualListbox()
</script>
{% include 'message.html' %}
</body>

templates/message.html
{% load static %}
<!-- Toastr -->
<link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
{% if messages %}
{% for message in messages %}
<script>

  var message_type = `{{ message.tags }}`;

  if (message_type == 'info') {
    toastr.info(`{{ message }}`);

  } else if (message_type == 'success') {
    toastr.success(`{{ message }}`);
    
  } else if (message_type == 'warning') {
    toastr.warning(`{{ message }}`);
    
  } else if (message_type == 'error') {
    toastr.error(`{{ message }}`);
    
  }

  
</script>
{% endfor %}
{% endif %}

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a  class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          
          <li class="nav-header">Main</li>
          <li class="nav-item">
            <a href="{% url 'app:group' %}" class="nav-link {{ group_page_active }} ">
              <i class="nav-icon fas fa-users"></i>
              <p>
                Toparlar
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'app:users' %}" class="nav-link {{ users_page_active }}">
              <i class="nav-icon fa fa-user-alt"></i>
              <p>
                Ulanjylar
              </p>
            </a>
          </li>
          
          <li class="nav-header"></li>
          <li class="nav-item">
            <a href="{% url 'app:logout' %}" class="nav-link">
              <i class="nav-icon fas fa-sign-out-alt"></i>
              <p>
                Hasapdan çyk
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/users_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>

  <!-- Google Font: Source Sans Pro -->
  <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
     <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  {% include 'nav.html' %}

  {% include 'sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Ulanjy goşmak</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'app:users' %}">Ulanjylar</a></li>
              <li class="breadcrumb-item active">Ulanjy gos</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3"></div>
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Formy doldyryň</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{% url 'app:users_add' %}" method="post">{% csrf_token %}
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Ady</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ady" name="first_name">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Familýasy</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Familýasy" name="last_name">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Ulanyjy ady</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Ulanyjy ady" name="user_name">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Açar sözi</label>
                        <input type="password" class="form-control" id="exampleInputEmail1" placeholder="Açar sözi" name="password">
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Degişli toparlary</label>
                    <select class="duallistbox" multiple="multiple" name="user_groups">
                      {% for user_group in user_groups %}
                      <option value="{{ user_group.id }}">{{ user_group.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Degişli Rugsatlary</label>
                    <select class="duallistbox" multiple="multiple" name="user_permissions">
                      {% for user_permission in user_permissions %}
                      <option value="{{ user_permission.0 }}">{{ user_permission.1 }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>
          <div class="col-md-3"></div>
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.2.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- bs-custom-file-input -->
<script src="{% static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!-- <script src="{% static 'dist/js/demo.js' %}"></script> -->
<!-- Select2 -->
<script src="{% static 'plugins/select2/js/select2.full.min.js' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
//Bootstrap Duallistbox
$('.duallistbox').bootstrapDualListbox()

</script>
{% include 'message.html' %}
</body>